spring:
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
mybatis:
  type-aliases-package: com.zsm.tk.model
  mapper-locations: com/zsm/tk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

